### ISSUE TITLE
set metric does not work in route-map (argument is malformed)

### ISSUE THREAD

**Issue by thilse** [ocochard/BSDRP#21]
It seems to be specific to bsdrp (at least version 1.90). The same command is working under freebsd 11.1 and frr 3.0.3 (build yesterday from ports). 

Here the problem:

[root@router]~# vtysh

Hello, this is FRRouting (version 3.0.3).
Copyright 1996-2005 Kunihiro Ishiguro, et al.

router.bsdrp.net# conf t
router.bsdrp.net(config)# ip prefix-list NETZ1 seq 5 permit 192.168.0.0/20
router.bsdrp.net(config)# route-map WEG1_v4 permit 10
router.bsdrp.net(config-route-map)#  match ip address prefix-list NETZ1
router.bsdrp.net(config-route-map)# set metric 50
% Argument is malformed.
router.bsdrp.net(config-route-map)#

**Comment by ocochard** [comment]
Problem fixed since… some versions (not reproductible on 1.96).
