### ISSUE TITLE
Error while upgrading to 1.91

### ISSUE THREAD

**Issue by bodems** [ocochard/BSDRP#23]
When upgrading from 1.90 to 1.91, I get the following error:
```
[root@bgp2]/usr/local/etc# fetch 'https://bodems.net/BSDRP-1.91-upgrade-amd64-vga.img.xz' -o - | xzcat | upgrade
-                                             100% of   93 MB   28 kBps 56m33s
931707+0 records in
7278+1 records out
477033984 bytes transferred in 3393.987416 secs (140553 bytes/sec)
** /dev/vtbd0s2a (NO WRITE)
** Last Mounted on /usr/obj/BSDRP.amd64/_.mnt
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3 - Check Connectivity
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cyl groups
15539 files, 818985 used, 97120 free (1048 frags, 12009 blocks, 0.1% fragmentation)
umount: unmount of /cfg failed: Device busy
EXIT: ERROR: Can't umount /cfg
```
Any idea about this?

**Comment by ocochard** [comment]
Oh no 'umount: unmount of /cfg failed: Device busy'
I've believe to have fixed this problem: Do you have autosave enabled ?

**Comment by bodems** [comment]
Yes, autosave is enabled. Is there anything I can test or should I just disable autosave?

**Comment by ocochard** [comment]
What I mean is I've improved the upgrade script of 1.91 release (check [this commit](https://github.com/ocochard/BSDRP/commit/aa361de55b4a1dba2bf825bdf486abf2d7a93df8#diff-f0d55aca13dca60148493a8e8f6dd5df) and [this one](https://github.com/ocochard/BSDRP/commit/ac55fc8b9baf000afe49b412fd584e0c8b662e38#diff-f0d55aca13dca60148493a8e8f6dd5df)), but when you're upgrading a 1.90, it still the upgrade script 1.90 that is used :-(

For fixing your error, try to issue a second time the upgrade process after the first one failed: It (theorically) should works the second time.
Once upgraded to 1.91 (and rebooted), you can verify if the new upgrade script is better by upgrading it to same 1.91 version( it will be a useless upgrade): it should works fine.
