### ISSUE TITLE
Suggestion - Change from bgpq3 to bgpq4 on next releases

### ISSUE THREAD

**Issue by fischerdouglas** [ocochard/BSDRP#32]
bgpq4 was forked from bgpq3 almost a year ago.

The contributors are very active since then. and received a few new features and several improvements.

bgpq4 is also available on https://www.freshports.org/net-mgmt/bgpq4

No extra dependencies.

My suggestion for the next releases.

**Comment by ocochard** [comment]
Done into https://github.com/ocochard/BSDRP/commit/44a9c8c46a13264b86cca89b106286447949e262
