### ISSUE TITLE
`config rollback` is always failed.

### ISSUE THREAD

**Issue by yasuoohno** [ocochard/BSDRP#33]
Hi,

I cannot do rollback configuration with `config rollback`.

```
[root@router]~# config rollback
Rollback the archived configuration
This script is already running (file /var/run/config.bsdrp.lock detected or /var full)
```

I think it's trying to get the lock twice:

https://github.com/ocochard/BSDRP/blob/3497f08b1ea2f0de7514e4fefd98f9c778ff65bf/BSDRP/Files/usr/local/sbin/config#L323
https://github.com/ocochard/BSDRP/blob/3497f08b1ea2f0de7514e4fefd98f9c778ff65bf/BSDRP/Files/usr/local/sbin/config#L344

**Comment by ocochard** [comment]
Thanks for the report, fixed on https://github.com/ocochard/BSDRP/commit/c2c30bf8d2b12299eaa095c186600b7b26d7885c
