### ISSUE TITLE
Duplicates packets with Carp and ECMP

### ISSUE THREAD

**Issue by thetzim** [ocochard/BSDRP#39]
packets entering the router on a carp interface towards a destination having multiple routes in table (bird with netlink flavor) gets routed to all nexthops. Destination receives duplicates packets (one for each router).

The carp interface is the gateway for hosts on a vlan.

**Comment by thetzim** [comment]
I just opened PR 21168 on the matter.

**Comment by ocochard** [comment]
I think the correct PR was [this one](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271168)
Now, some advice to "fish" an FreeBSD developer (should be the same for all OpenSource project):
1. You should provide the simplest shell script to reproduce your error (very easy using vnet jail).
2. Once you done step 1, convert your script as a regression tests and submit it as to improve FreeBSD. Example of [multipath regression](https://github.com/freebsd/freebsd-src/blob/main/tests/sys/net/routing/test_rtsock_multipath.py) tests.

With this, you should be able to fish a big developer :-)

**Comment by thetzim** [comment]
Thanks for the advices. 
I, indeed, filled the PR too fast, as the problem was elsewhere. 
After more investigation on the issue, it appears that the culprit was the second carp router which deconfigured carp interface continued to process packets to the carp MAC address.

Configuration / deconfiguration of interfaces seems to be bogus somewhere else.
