### ISSUE TITLE
Add net/kea in preparation for net/isc-dhcp44-server's deprecation

### ISSUE THREAD

**Issue by jlduran** [ocochard/BSDRP#43]
net/isc-dhcp44-server [has been deprecated](https://www.isc.org/blogs/isc-dhcp-eol/). Add net/kea to BSDRP-pkglist as the most likely successor for its replacement.
As a side note, [KeaMA](https://dhcp.isc.org) can be used to migrate the configuration labs/examples.

**Comment by ocochard** [comment]
Thanks for the update… but there is something I don’t understand with net/kea:

- net/isc-dhcp44-server is a 7MB package, 0 dependency, package size (includings deps): 7MB
- net/kea is a 74MB (!) package AND brings crazy huge lib-boost (183M) and devel/icu (54MB) and devel/log4cplus (1MB), then it requires about 300MB of binary.
This is a no go for net/kea

**Comment by jlduran** [comment]
> Thanks for the update… but there is something I don’t understand with net/kea:
> 
> * net/isc-dhcp44-server is a 7MB package, 0 dependency, package size (includings deps): 7MB
> * net/kea is a 74MB (!) package AND brings crazy huge lib-boost (183M) and devel/icu (54MB) and devel/log4cplus (1MB), then it requires about 300MB of binary.
>   This is a no go for net/kea

Yes, this is something I've been struggling with for a while when creating that package. I'll close this issue and look into other alternatives (OpenBSD must have something). Thanks for the heads up!
