### ISSUE TITLE
Restore the functionality of the early entropy seed file

### ISSUE THREAD

**Issue by jlduran** [ocochard/BSDRP#46]
After https://github.com/freebsd/freebsd-src/commit/e5579f98c02ff64b0c305f6731c3557ba69c2d25, the patch:
https://github.com/ocochard/BSDRP/blob/e2c611657408935b391efa2226bd0ab768135d89/BSDRP/patches/freebsd.random.patch#L10
will not work because the NanoBSD script now sets `entropy_boot_file="NO"`.
To maintain the current behavior, the following parameters would need to be explicitly set:

- In `/boot/loader.conf`:
  ```
  entropy_cache_load="YES"
  kern.random.initial_seeding.disable_bypass_warnings="0"
  ```
- In `/etc/defaults/vendor.conf`:
  ```
  entropy_boot_file="/boot/entropy"
  ```

In order to take advantage of that entropy boot file, `kern.random.initial_seeding.bypass_before_seeding` should be set to `0`, but this is outside the scope of this issue.

Reference: [random(4)](https://man.freebsd.org/cgi/man.cgi?query=random&sektion=4)

**Comment by ocochard** [comment]
Thank you so much for taking the time to update FreeBSD’s NanoBSD and for communicating with downstream projects. This is greatly appreciated!"

**Comment by jlduran** [comment]
Happy to help!
