### ISSUE TITLE
 trying to upgrade fails with error

### ISSUE THREAD

**Issue by outbackdingo** [ocochard/BSDRP#9]
-rw-r--r--   1 root   dingo  62809688 Sep 26 21:55 BSDRP-1.61-full-amd64-vga.img.xz
-rw-r--r--   1 root   dingo  62728164 Sep 26 21:55 BSDRP-1.61-upgrade-amd64-vga.img.xz

ssh dingo@162.217.xxx.xxx cat /home/dingo/BSDRP-1.61-upgrade-amd64-vga.img.xz | xzcat | upgrade
Password for dingo@hardened.xxxxxxxxx.com:
dd: /dev/ada0s2: short write on character device
dd: /dev/ada0s2: end of device
465920+0 records in
3639+1 records out
238500864 bytes transferred in 26.083972 secs (9143579 bytes/sec)
EXIT: ERROR: Can't install the upgrade on /dev/ada0s2

trying to upgrade fails with error
+ set -eu
+ uname -m
+ ARCH=amd64
+ GPT=false
+ [ -f /etc/nanobsd.conf ]
+ . /etc/nanobsd.conf
+ NANO_DRIVE=ufs/BSDRP
+ LABEL=BSDRP
+ grep -q =gpt/ /etc/nanobsd.conf
+ get_info
+ false
+ mbr_get_info
+ mount
+ grep -q '/dev/ufs/BSDRPs1a on / '
+ CURRENT_SLICE=s1
+ CURRENT_PART=1
+ NEXT_SLICE=s2
+ NEXT_PART=2
+ BSD_SLICE=a
+ NEXT_LABEL_ID=s2a
+ CURRENT_LABEL_ID=s1a
+ glabel status
+ grep ufs/BSDRPs1a
+ awk '{ s=$3; sub(/s[12]a$/, "", s); print s; }'
+ boot_dev=/dev/ada0
+ [ -z /dev/ada0 ]
+ return 0
+ write_new_image
+ [ -c /dev/ada0s2 ]
+ dd if=/dev/zero of=/dev/ada0s2 bs=1m count=1
+ dd of=/dev/ada0s2 obs=64k
Password for dingo@hardened.xxxxxxxxx.com:
dd: /dev/ada0s2: short write on character device
dd: /dev/ada0s2: end of device
465920+0 records in
3639+1 records out
238500864 bytes transferred in 28.496121 secs (8369590 bytes/sec)
+ die 'ERROR: Can'\''t install the upgrade on /dev/ada0s2'
+ echo -n 'EXIT: '
EXIT: + echo 'ERROR: Can'\''t install the upgrade on /dev/ada0s2'
ERROR: Can't install the upgrade on /dev/ada0s2
+ exit 1

 gpart show
=>     63  2030049  ada0  MBR  (991M)
       63   465822     1  freebsd  [active]  (227M)
   465885       63        - free -  (32K)
   465948   465822     2  freebsd  (227M)
   931770    32130     3  freebsd  (16M)
   963900  1066212     4  freebsd  (521M)

=>     0  465822  ada0s1  BSD  (227M)
       0      16          - free -  (8.0K)
      16  465806       1  !0  (227M)

=>     63  2030049  diskid/DISK-2010083100052C562C56  MBR  (991M)
       63   465822                                 1  freebsd  [active]  (227M)
   465885       63                                    - free -  (32K)
   465948   465822                                 2  freebsd  (227M)
   931770    32130                                 3  freebsd  (16M)
   963900  1066212                                 4  freebsd  (521M)

=>     0  465822  diskid/DISK-2010083100052C562C56s1  BSD  (227M)
       0      16                                      - free -  (8.0K)
      16  465806                                   1  !0  (227M)

**Comment by ocochard** [comment]
BSDRP version 1.61 is not released: Only 1.60 is available.
Disk size requirement changed from 512MB to 1GB for a fresh install of 1.60 release (only fresh install: upgrade is still possible to 1.60 on a previous BSDRP installed on a 512MB disk).
But for the next release (like 1.61 for your custom build), the upgrade image will be for 1GB disk only, then if your first installation is previous to 1.60, you need to issue this command line before starting an upgrade:
`system resize-system-slice 964000`
warning: In some case you need to use this command twice (after the first reboot).

**Comment by outbackdingo** [comment]
tried this though it seems to hang

./system resize-system-slice 964000
+ set -e
+ [ 2 -eq 0 ]
+ FIRST_OPTION=resize-system-slice
+ [ 2 -ge 2 ]
+ SECOND_OPTION=964000
+ [ 2 -ge 3 ]
+ THIRD_OPTION=''
+ resize_system_slice 964000
+ [ -z 964000 ]
+ echo 'This tool will expand the 2 systems slices to the given size.'
This tool will expand the 2 systems slices to the given size.
+ echo 'It'\''s only usefull for specific upgrade'
It's only usefull for specific upgrade
+ echo '- If a partition swaping is needed, system will reboot automatically at the end of first step'
- If a partition swaping is needed, system will reboot automatically at the end of first step
+ echo '  You need to restart this tool after the reboot for continuing'
  You need to restart this tool after the reboot for continuing
+ echo '- All files stored in /data partition will be destroyed!'
- All files stored in /data partition will be destroyed!
+ echo -n 'Do you want to continue or abort ? (y/a): '
Do you want to continue or abort ? (y/a): + USER_CONFIRM=''
+ [ '' != y -a '' != a ]
+ read USER_CONFIRM
y
+ [ y != y -a y != a ]
+ [ y = a ]
+ echo -n 'Checking disk size...'
Checking disk size...+ get_label
+ cut -d / -f 2 /etc/nanobsd.conf
+ local label=BSDRP
+ [ -n BSDRP ]
+ echo BSDRP
+ label=BSDRP
+ glabel status
+ awk '{ print $3; } '
+ grep BSDRPs1
+ cut -d s -f 1
+ boot_dev=ada0
+ [ -z ada0 ]
+ gpart show ada0
+ grep ada0
+ cut -d ' ' -f 3
+ tr -s ' '
+ disk_size=2030049
+ [ -z 2030049 ]
+ minimum_size=1992260
+ [ 2030049 -lt 1992260 ]
+ . /etc/nanobsd.conf
+ NANO_DRIVE=ufs/BSDRP
+ mount /dev/ufs/BSDRPs1a

**Comment by outbackdingo** [comment]
So on the first system that failed to resize, i did get it to reboot and it came back, however dmesg
just after the reboot is showing 
GEOM_PART: integrity check failed (ada0s2, BSD)
GEOM_PART: integrity check failed (diskid/DISK-2010083100052C562C56s2, BSD)

guess maybe the disk is bad? or somehow corrupted.
ada0 at ata0 bus 0 scbus0 target 0 lun 0
ada0: <SMART IDE 20060811> ATA device
ada0: Serial Number 2010083100052C562C56
ada0: 16.700MB/s transfers (WDMA2, PIO 512bytes)
ada0: 991MB (2030112 512 byte sectors)
ada0: Previously was known as ad0
GEOM_PART: integrity check failed (ada0s2, BSD)
GEOM_PART: integrity check failed (diskid/DISK-2010083100052C562C56s2, BSD)
SMP: AP CPU #1 Launched!
Timecounter "TSC-low" frequency 1795533610 Hz quality 1000
Root mount waiting for: usbus3 usbus2 usbus1 usbus0
uhub0: 2 ports with 2 removable, self powered
uhub1: 2 ports with 2 removable, self powered
uhub2: 2 ports with 2 removable, self powered
Root mount waiting for: usbus3
Root mount waiting for: usbus3
uhub3: 6 ports with 6 removable, self powered
Trying to mount root from ufs:/dev/ufs/BSDRPs1a [ro]...
GEOM_PART: integrity check failed (diskid/DISK-2010083100052C562C56s2, BSD)
GEOM_PART: integrity check failed (diskid/DISK-2010083100052C562C56s2, BSD)

**Comment by outbackdingo** [comment]
and this is how i recovered to a fully working system

[root@router1]~# dd if=/dev/ada0s1 of=/dev/ada0s2
^C23475+0 records in
23475+0 records out
12019200 bytes transferred in 13.301065 secs (903627 bytes/sec)
[root@router1]~# gpart show
=>     63  2030049  ada0  MBR  (991M)
       63   465822     1  freebsd  [active]  (227M)
   465885       63        - free -  (32K)
   465948   465822     2  freebsd  (227M)
   931770    32130     3  freebsd  (16M)
   963900  1066212     4  freebsd  (521M)

=>     0  465822  ada0s1  BSD  (227M)
       0      16          - free -  (8.0K)
      16  465806       1  !0  (227M)

=>     0  465822  ada0s2  BSD  (227M)
       0      16          - free -  (8.0K)
      16  465806       1  !0  (227M)

=>     63  2030049  diskid/DISK-2010083100052C562C56  MBR  (991M)
       63   465822                                 1  freebsd  [active]  (227M)
   465885       63                                    - free -  (32K)
   465948   465822                                 2  freebsd  (227M)
   931770    32130                                 3  freebsd  (16M)
   963900  1066212                                 4  freebsd  (521M)

=>     0  465822  diskid/DISK-2010083100052C562C56s1  BSD  (227M)
       0      16                                      - free -  (8.0K)
      16  465806                                   1  !0  (227M)

=>     0  465822  diskid/DISK-2010083100052C562C56s2  BSD  (227M)
       0      16                                      - free -  (8.0K)
      16  465806                                   1  !0  (227M)

[root@router1]~# system resize-system-slice 964000
+ set -e
+ [ 2 -eq 0 ]
+ FIRST_OPTION=resize-system-slice
+ [ 2 -ge 2 ]
+ SECOND_OPTION=964000
+ [ 2 -ge 3 ]
+ THIRD_OPTION=''
+ resize_system_slice 964000
+ [ -z 964000 ]
+ echo 'This tool will expand the 2 systems slices to the given size.'
This tool will expand the 2 systems slices to the given size.
+ echo 'It'\''s only usefull for specific upgrade'
It's only usefull for specific upgrade
+ echo '- If a partition swaping is needed, system will reboot automatically at the end of first step'
- If a partition swaping is needed, system will reboot automatically at the end of first step
+ echo '  You need to restart this tool after the reboot for continuing'
  You need to restart this tool after the reboot for continuing
+ echo '- All files stored in /data partition will be destroyed!'
- All files stored in /data partition will be destroyed!
+ echo -n 'Do you want to continue or abort ? (y/a): '
Do you want to continue or abort ? (y/a): + USER_CONFIRM=''
+ [ '' != y -a '' != a ]
+ read USER_CONFIRM
y
+ [ y != y -a y != a ]
+ [ y = a ]
+ echo -n 'Checking disk size...'
Checking disk size...+ get_label
+ cut -d / -f 2 /etc/nanobsd.conf
+ local label=BSDRP
+ [ -n BSDRP ]
+ echo BSDRP
+ label=BSDRP
+ glabel status
+ grep BSDRPs1
+ cut -d s -f 1
+ awk '{ print $3; } '
+ boot_dev=ada0
+ [ -z ada0 ]
+ gpart show ada0
+ grep ada0
+ tr -s ' '
+ cut -d ' ' -f 3
+ disk_size=2030049
+ [ -z 2030049 ]
+ minimum_size=1992260
+ [ 2030049 -lt 1992260 ]
+ . /etc/nanobsd.conf
+ NANO_DRIVE=ufs/BSDRP
+ mount /dev/ufs/BSDRPs1a
+ resize_system
+ echo -n 'Resizing partition...'
Resizing partition...+ gpart delete -i 4 ada0
ada0s4 deleted
+ gpart delete -i 3 ada0
ada0s3 deleted
+ gpart delete -i 2 ada0
ada0s2 deleted
+ gpart resize -i 1 -a 4k -s 964000 ada0
ada0s1 resized
+ gpart commit ada0s1
+ gpart add -t freebsd -i 2 -a 4k -s 964000 ada0
ada0s2 added
+ gpart add -t freebsd -i 3 -a 4k -s 16M ada0
ada0s3 added
+ gpart add -t freebsd -i 4 -a 4k ada0
ada0s4 added
+ newfs -b 4096 -f 512 -i 8192 -U -L BSDRPs3 /dev/ada0s3
/dev/ada0s3: 16.0MB (32697 sectors) block size 4096, fragment size 512
        using 4 cylinder groups of 3.99MB, 1022 blks, 512 inodes.
        with soft updates
super-block backups (for fsck_ffs -b #) at:
 144, 8320, 16496, 24672
+ newfs -b 4096 -f 512 -i 8192 -U -L BSDRPs4 /dev/ada0s4
/dev/ada0s4: 33.8MB (69237 sectors) block size 4096, fragment size 512
        using 4 cylinder groups of 8.45MB, 2164 blks, 1088 inodes.
        with soft updates
super-block backups (for fsck_ffs -b #) at:
 144, 17456, 34768, 52080
+ config save
Archiving previous configuration files...
Saving configuration...


Done.
+ echo Done
Done
+ echo 'Your system slice were correctly resized'
Your system slice were correctly resized
+ return 0
[root@router1]~# 
[root@router1]~# 
[root@router1]~# gpart show
=>     63  2030049  ada0  MBR  (991M)
       63   963963     1  freebsd  [active]  (471M)
   964026       63        - free -  (32K)
   964089   963900     2  freebsd  (471M)
  1927989       63        - free -  (32K)
  1928052    32697     3  freebsd  (16M)
  1960749       63        - free -  (32K)
  1960812    69237     4  freebsd  (34M)
  2030049       63        - free -  (32K)

=>     0  963963  ada0s1  BSD  (471M)
       0      16          - free -  (8.0K)
      16  465806       1  !0  (227M)
  465822  498141          - free -  (243M)

=>     63  2030049  diskid/DISK-2010083100052C562C56  MBR  (991M)
       63   963963                                 1  freebsd  [active]  (471M)
   964026       63                                    - free -  (32K)
   964089   963900                                 2  freebsd  (471M)
  1927989       63                                    - free -  (32K)
  1928052    32697                                 3  freebsd  (16M)
  1960749       63                                    - free -  (32K)
  1960812    69237                                 4  freebsd  (34M)
  2030049       63                                    - free -  (32K)

=>     0  963963  diskid/DISK-2010083100052C562C56s1  BSD  (471M)
       0      16                                      - free -  (8.0K)
      16  465806                                   1  !0  (227M)
  465822  498141                                      - free -  (243M)

[root@router1]~# ssh dingo@162.217.150.80 cat /home/dingo/BSDRP-1.61-upgrade-amd64-vga.img.xz | xzcat | upgrade
+ set -eu
+ uname -m
+ ARCH=amd64
+ GPT=false
+ [ -f /etc/nanobsd.conf ]
+ . /etc/nanobsd.conf
+ NANO_DRIVE=ufs/BSDRP
+ LABEL=BSDRP
+ grep -q =gpt/ /etc/nanobsd.conf
+ get_info
+ false
+ mbr_get_info
+ mount
+ grep -q '/dev/ufs/BSDRPs1a on / '
+ CURRENT_SLICE=s1
+ CURRENT_PART=1
+ NEXT_SLICE=s2
+ NEXT_PART=2
+ BSD_SLICE=a
+ NEXT_LABEL_ID=s2a
+ CURRENT_LABEL_ID=s1a
+ glabel status
+ grep ufs/BSDRPs1a
+ awk '{ s=$3; sub(/s[12]a$/, "", s); print s; }'
+ boot_dev=/dev/ada0
+ [ -z /dev/ada0 ]
+ return 0
+ write_new_image
+ [ -c /dev/ada0s2 ]
+ dd if=/dev/zero of=/dev/ada0s2 bs=1m count=1
+ dd of=/dev/ada0s2 obs=64k
Password for dingo@hardened.optimcloud.com:
963837+0 records in
7529+1 records out
493484544 bytes transferred in 50.820129 secs (9710415 bytes/sec)
+ fsck_ffs -n /dev/ada0s2a
** /dev/ada0s2a (NO WRITE)
** Last Mounted on /usr/obj/BSDRP.amd64/_.mnt
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3 - Check Connectivity
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cyl groups
12327 files, 516931 used, 430440 free (2432 frags, 53501 blocks, 0.3% fragmentation)
+ false
+ tunefs -L BSDRPs2a /dev/ada0s2a
+ [ -d /tmp/sysupgrade ]
+ mkdir /tmp/sysupgrade
+ mount /dev/ufs/BSDRPs2a /tmp/sysupgrade
+ [ -f /boot/loader.conf.local ]
+ cp /boot/loader.conf.local /tmp/sysupgrade/boot
+ [ -f /boot.config ]
+ cmp -s /boot.config /tmp/sysupgrade/boot.config
+ sed -i '' s/BSDRPs1a/BSDRPs2a/g /tmp/sysupgrade/etc/fstab
+ sed -i '' s/BSDRPs1a/BSDRPs2a/g /tmp/sysupgrade/conf/base/etc/fstab
+ sed -i '' s/BSDRPs1a/BSDRPs2a/g /etc/fstab
+ [ -f /tmp/sysupgrade/usr/local/sbin/post-upgrade ]
+ cp /tmp/sysupgrade/usr/local/sbin/post-upgrade /tmp/post-upgrade
+ umount /tmp/sysupgrade
+ rm -r /tmp/sysupgrade
+ mount
+ grep -q /cfg
+ mount /cfg
+ cp /etc/fstab /cfg
+ umount /cfg
+ return 0
+ boot_modif
+ false
+ mbr_boot_modif
+ boot0cfg -s 2 -t 18 -v /dev/ada0
#   flag     start chs   type       end chs       offset         size
1   0x80      0:  1: 1   0xa5    956:  5:63           63       963963
2   0x00    956:  7: 1   0xa5   1023:255:63       964089       963900
3   0x00   1023:255:63   0xa5   1023:255:63      1928052        32697
4   0x00   1023:255:63   0xa5   1023:255:63      1960812        69237

version=2.0  drive=0x80  mask=0x3  ticks=18  bell=# (0x23)
options=packet,update,nosetdrv
volume serial ID 9090-9090
default_selection=F2 (Slice 2)
+ gpart set -a active -i 2 /dev/ada0
active set on ada0s2
+ return 0
+ return 0
+ echo 'BSDRP Upgrade complete'
BSDRP Upgrade complete
+ logger BSDRP Upgrade complete
+ [ -f /tmp/post-upgrade ]
+ echo 'Starting post-upgrade script...'
Starting post-upgrade script...
+ logger Starting post-upgrade script
+ chmod +x /tmp/post-upgrade
+ /tmp/post-upgrade /dev/ufs/BSDRPs2a
[root@router1]~# gpart show
=>     63  2030049  ada0  MBR  (991M)
       63   963963     1  freebsd  (471M)
   964026       63        - free -  (32K)
   964089   963900     2  freebsd  [active]  (471M)
  1927989       63        - free -  (32K)
  1928052    32697     3  freebsd  (16M)
  1960749       63        - free -  (32K)
  1960812    69237     4  freebsd  (34M)
  2030049       63        - free -  (32K)

=>     0  963963  ada0s1  BSD  (471M)
       0      16          - free -  (8.0K)
      16  465806       1  !0  (227M)
  465822  498141          - free -  (243M)

=>     0  963900  ada0s2  BSD  (471M)
       0      16          - free -  (8.0K)
      16  963821       1  !0  (471M)
  963837      63          - free -  (32K)

=>     63  2030049  diskid/DISK-2010083100052C562C56  MBR  (991M)
       63   963963                                 1  freebsd  (471M)
   964026       63                                    - free -  (32K)
   964089   963900                                 2  freebsd  [active]  (471M)
  1927989       63                                    - free -  (32K)
  1928052    32697                                 3  freebsd  (16M)
  1960749       63                                    - free -  (32K)
  1960812    69237                                 4  freebsd  (34M)
  2030049       63                                    - free -  (32K)

=>     0  963963  diskid/DISK-2010083100052C562C56s1  BSD  (471M)
       0      16                                      - free -  (8.0K)
      16  465806                                   1  !0  (227M)
  465822  498141                                      - free -  (243M)

=>     0  963900  diskid/DISK-2010083100052C562C56s2  BSD  (471M)
       0      16                                      - free -  (8.0K)
      16  963821                                   1  !0  (471M)
  963837      63                                      - free -  (32K)

[root@router1]~# reboot
+ set -e
+ [ 1 -eq 0 ]
+ FIRST_OPTION=reboot
+ [ 1 -ge 2 ]
+ SECOND_OPTION=''
+ [ 1 -ge 3 ]
+ THIRD_OPTION=''
+ sys_reboot
+ check_cfg
+ sh /etc/rc.conf
+ echo 'Checking if configuration is saved...'
Checking if configuration is saved...
+ set +e
+ config diff quiet
+ [ 0 -eq 1 ]
+ set -e
+ echo Rebooting...
Rebooting...
+ shutdown -r now
Shutdown NOW!
shutdown: [pid 2777]
[root@router1]~#
*** FINAL System shutdown message from root@router1.optimcloud.com ***
System going down IMMEDIATELY
System shutdown time has arrived
Connection to router1.optimcloud.com closed by remote host.
Connection to router1.optimcloud.com closed.
